version: '3.5'

services:
  calendar-api:
    container_name: calendar-api
    build: 
        context: ./
        dockerfile: Dockerfile
    ports:
      - "8050:80"
    depends_on: 
      - "postgresdb"
  postgresdb:
    container_name: calendarDb
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "cihan8"
    ports:
      - "15432:5432"
    restart: always
    